export const preguntas = [
    // Categoría: Divertidas
    { id: 1, categoria: "divertida", texto: "Si pudieras ser un personaje ficticio, ¿quién te gustaría ser y por qué?" },
    { id: 2, categoria: "divertida", texto: "¿Qué piensas mientras te duchas?" },
    { id: 3, categoria: "divertida", texto: "¿Cuál es la peor broma que podrías hacerme?" },
    { id: 4, categoria: "divertida", texto: "¿Qué es lo más vergonzoso que has hecho en público?" },
    { id: 5, categoria: "divertida", texto: "¿Cuáles son tus principales manías?" },
    { id: 6, categoria: "divertida", texto: "¿Cuál ha sido la canción más 'vergonzosa' que te ha gustado?" },
    { id: 7, categoria: "divertida", texto: "¿Quién fue tu primer crush?" },
    { id: 8, categoria: "divertida", texto: "¿Cuál de mis amigos/as es tu favorito/a?" },
    { id: 9, categoria: "divertida", texto: "¿Qué es lo más raro que has comido en tu vida?" },
    { id: 10, categoria: "divertida", texto: "¿Cuál fue tu primer flechazo con un famoso?" },
    { id: 11, categoria: "divertida", texto: "¿Qué fue lo último que buscaste en Google?" },
    { id: 12, categoria: "divertida", texto: "¿Qué es lo más raro que harías para ganar una apuesta?" },
    { id: 13, categoria: "divertida", texto: "¿Cuál fue tu peor primera cita?" },
    { id: 14, categoria: "divertida", texto: "Si fueras un animal, ¿cuál serías y por qué?" },
    { id: 15, categoria: "divertida", texto: "¿Qué superpoder chistoso te gustaría tener?" },
    { id: 16, categoria: "divertida", texto: "¿Cuál es la tendencia de moda más vergonzosa que has seguido?" },
    { id: 17, categoria: "divertida", texto: "¿Qué harías si me escuchas decir algo absurdo dormido/a?" },
    { id: 18, categoria: "divertida", texto: "Si tuvieras que participar en un reality de televisión, ¿cuál elegirías?" },
    { id: 19, categoria: "divertida", texto: "¿Qué película horrorosa está entre tus favoritas?" },
    { id: 20, categoria: "divertida", texto: "¿Cuál es el peor regalo que has recibido?" },

    // Categoría: Picantes
    { id: 21, categoria: "picante", texto: "¿Qué es algo que nunca te has atrevido a pedir en la cama?" },
    { id: 22, categoria: "picante", texto: "¿Tienes algún fetiche que yo no conozca?" },
    { id: 23, categoria: "picante", texto: "¿Qué prenda de mi armario te parece más sexy?" },
    { id: 24, categoria: "picante", texto: "¿Te gusta el sexting?" },
    { id: 25, categoria: "picante", texto: "Si pudiéramos estar en cualquier lugar ahora, ¿dónde sería y qué haríamos?" },
    { id: 26, categoria: "picante", texto: "¿Qué puntuación te darías del 1 al 10 en la cama?" },
    { id: 27, categoria: "picante", texto: "¿Cuál es el lugar más extraño en el que te gustaría hacer el amor?" },
    { id: 28, categoria: "picante", texto: "¿Qué es lo que más te excita?" },
    { id: 29, categoria: "picante", texto: "¿Cuál es tu mayor fantasía conmigo?" },
    { id: 30, categoria: "picante", texto: "¿Cuál es tu postura sexual preferida?" },
    { id: 31, categoria: "picante", texto: "¿Prefieres uno rapidito, de aquí te agarro y lo hacemos, o uno más lento?" },
    { id: 32, categoria: "picante", texto: "¿Cuál es tu lugar preferido para besarme?" },
    { id: 33, categoria: "picante", texto: "¿Qué juguete sexual es tu favorito?" },
    { id: 34, categoria: "picante", texto: "¿Qué es lo más atrevido que harías en público conmigo?" },
    { id: 35, categoria: "picante", texto: "¿Fantaseaste conmigo alguna vez antes de empezar a salir juntos/as?" },
    { id: 36, categoria: "picante", texto: "¿Qué piensas del poliamor?" },
    { id: 37, categoria: "picante", texto: "En tres palabras, ¿cómo describirías mi personalidad en la cama?" },
    { id: 38, categoria: "picante", texto: "¿Has tenido algún sueño erótico conmigo?" },
    { id: 39, categoria: "picante", texto: "¿Tienes alguna experiencia inconfesable?" },
    { id: 40, categoria: "picante", texto: "¿Cambiarías alguna cosa de nuestra vida sexual?" },

    // Categoría: Románticas
    { id: 41, categoria: "romántica", texto: "¿Qué pensaste de mí la primera vez que me viste?" },
    { id: 42, categoria: "romántica", texto: "¿Cuál es tu recuerdo favorito de los/las dos juntos/as?" },
    { id: 43, categoria: "romántica", texto: "¿Qué te gustaría que hiciéramos más a menudo?" },
    { id: 44, categoria: "romántica", texto: "¿Qué palabra usarías para definir nuestra relación?" },
    { id: 45, categoria: "romántica", texto: "¿Cuál es tu lugar favorito para pasar tiempo juntos?" },
    { id: 46, categoria: "romántica", texto: "¿Qué canción te recuerda a mí?" },
    { id: 47, categoria: "romántica", texto: "¿Qué parte de mi cuerpo te gusta más?" },
    { id: 48, categoria: "romántica", texto: "¿Qué promesa romántica me harías ahora mismo?" },
    { id: 49, categoria: "romántica", texto: "¿Qué escena de película te gustaría recrear conmigo?" },
    { id: 50, categoria: "romántica", texto: "¿Qué crees que podríamos mejorar de nuestra relación?" },
    { id: 51, categoria: "romántica", texto: "¿Qué te pareció nuestro primer beso?" },
    { id: 52, categoria: "romántica", texto: "¿Qué característica de mi personalidad te parece irresistible?" },
    { id: 53, categoria: "romántica", texto: "¿Crees en las almas gemelas?" },
    { id: 54, categoria: "romántica", texto: "¿Qué es lo que más te gusta de nuestra relación?" },
    { id: 55, categoria: "romántica", texto: "¿Qué te enamoró de mí?" },
    { id: 56, categoria: "romántica", texto: "¿Qué canción crees que nos representa mejor como pareja?" },
    { id: 57, categoria: "romántica", texto: "Si me conocieras de nuevo, ¿crees que te volverías a enamorar de mí?" },
    { id: 58, categoria: "romántica", texto: "¿Piensas que soy el amor de tu vida?" },
    { id: 59, categoria: "romántica", texto: "¿Cómo nos imaginas dentro de unos años?" },
    { id: 60, categoria: "romántica", texto: "¿Cuál es el momento más romántico que recuerdas conmigo?" },

    // Categoría: Profundas
    { id: 61, categoria: "profunda", texto: "Si pudieras intercambiarte con alguien por un día, ¿a quién elegirías?" },
    { id: 62, categoria: "profunda", texto: "¿Cuál es tu recuerdo favorito de la infancia?" },
    { id: 63, categoria: "profunda", texto: "¿Qué es lo que más valoras de nuestra relación?" },
    { id: 64, categoria: "profunda", texto: "¿Cuál es el mejor consejo que has recibido?" },
    { id: 65, categoria: "profunda", texto: "¿Preferirías volver al pasado o viajar al futuro?" },
    { id: 66, categoria: "profunda", texto: "¿Cómo te gustaría que te recordaran algún día?" },
    { id: 67, categoria: "profunda", texto: "¿Crees en las segundas oportunidades?" },
    { id: 68, categoria: "profunda", texto: "¿Qué crees que nos hace únicos/as como pareja?" },
    { id: 69, categoria: "profunda", texto: "Si pudiéramos vivir en cualquier parte del mundo, ¿dónde te gustaría que lo hiciéramos?" },
    { id: 70, categoria: "profunda", texto: "¿Cuándo fue la última vez que lloraste y por qué?" },
    { id: 71, categoria: "profunda", texto: "Si pudieras hacer cualquier trabajo en el mundo, ¿cuál sería?" },
    { id: 72, categoria: "profunda", texto: "¿Cuál es tu mayor temor sobre nuestra relación?" },
    { id: 73, categoria: "profunda", texto: "¿Qué significa para ti la palabra compromiso?" },
    { id: 74, categoria: "profunda", texto: "¿Cuál es el mayor secreto que has ocultado a tus padres?" },
    { id: 75, categoria: "profunda", texto: "¿Qué es lo más ilegal que has hecho nunca?" },
    { id: 76, categoria: "profunda", texto: "Si no tuvieras que trabajar nunca más, ¿qué harías?" },
    { id: 77, categoria: "profunda", texto: "¿Cuándo fue la última vez que te dí celos?" },
    { id: 78, categoria: "profunda", texto: "¿Qué es lo último que has soñado?" },
    { id: 79, categoria: "profunda", texto: "¿De qué famoso te gustaría ser muy amigo/a?" },
    { id: 80, categoria: "profunda", texto: "¿Cuál es la mentira más grande que has contado jamás?" }
];

export const retos = [
    // Categoría: divertidos
    { id: 1, categoria: "divertidos", texto: "Dúchate con la ropa puesta." },
    { id: 2, categoria: "divertidos", texto: "Haz una declaración de amor en cámara lenta." },
    { id: 3, categoria: "divertidos", texto: "Déjate maquillar y peinar por mí." },
    { id: 4, categoria: "divertidos", texto: "Imita a alguien conocido (presentador, actor, personaje de dibujos animados...) durante unos minutos." },
    { id: 5, categoria: "divertidos", texto: "Haz un selfie ridículo de los/las dos y ponlo de foto de perfil durante al menos una hora." },
    { id: 6, categoria: "divertidos", texto: "Ponte una venda en los ojos y deja que te dé de comer algo secreto." },
    { id: 7, categoria: "divertidos", texto: "Habla con acento extranjero durante las siguientes 2 rondas." },
    { id: 8, categoria: "divertidos", texto: "Ponte un cubito de hielo en la ropa interior." },
    { id: 9, categoria: "divertidos", texto: "Intenta comer algo sin usar las manos." },
    { id: 10, categoria: "divertidos", texto: "Pídeme matrimonio de la forma más dramática posible." },

    // Categoría: sensuales
    { id: 11, categoria: "sensuales", texto: "Susúrrame algo excitante al oído." },
    { id: 12, categoria: "sensuales", texto: "Pon la canción con la que te gustaría tener sexo." },
    { id: 13, categoria: "sensuales", texto: "Dibuja el alfabeto con tu lengua en alguna parte de mi cuerpo." },
    { id: 14, categoria: "sensuales", texto: "Elige un juguete sexual online que te gustaría probar conmigo." },
    { id: 15, categoria: "sensuales", texto: "Hazme un baile erótico." },
    { id: 16, categoria: "sensuales", texto: "Quítame una prenda de ropa solo con la boca." },
    { id: 17, categoria: "sensuales", texto: "Dame un beso en tu lugar favorito de mi cuerpo." },
    { id: 18, categoria: "sensuales", texto: "Finge tener un orgasmo." },
    { id: 19, categoria: "sensuales", texto: "Ve a otra habitación y envíame un mensaje o un selfie sexy." },
    { id: 20, categoria: "sensuales", texto: "Véndate los ojos la próxima vez que hagamos el amor." },

    // Categoría: románticos
    { id: 21, categoria: "románticos", texto: "Bésame profundamente durante cinco (deliciosos) minutos." },
    { id: 22, categoria: "románticos", texto: "Abrázame en silencio durante un minuto." },
    { id: 23, categoria: "románticos", texto: "Escríbeme una carta de amor de, al menos, diez líneas." },
    { id: 24, categoria: "románticos", texto: "Susúrrame algo dulce y cariñoso al oído." },
    { id: 25, categoria: "románticos", texto: "Escribe las cinco cosas que más te gustan de mí." },
    { id: 26, categoria: "románticos", texto: "Cuéntame algo que nunca le hayas contado a nadie." },
    { id: 27, categoria: "románticos", texto: "Haz un dibujo de nuestra primera cita." },
    { id: 28, categoria: "románticos", texto: "Bésame en una parte inesperada de mi cuerpo." },
    { id: 29, categoria: "románticos", texto: "Dame una serenata con la canción que tú quieras." },
    { id: 30, categoria: "románticos", texto: "Mantén el contacto visual conmigo durante dos minutos." },

    // Categoría: curiosos
    { id: 31, categoria: "curiosos", texto: "Dame un masaje de cinco minutos." },
    { id: 32, categoria: "curiosos", texto: "Bésame en cinco sitios diferentes de mi cuerpo." },
    { id: 33, categoria: "curiosos", texto: "¡Intercambiemos la ropa!" },
    { id: 34, categoria: "curiosos", texto: "Declara tu amor en una canción o poema improvisado en 30 segundos." },
    { id: 35, categoria: "curiosos", texto: "Imítame unos minutos, remarcando todas mis manías." },
    { id: 36, categoria: "curiosos", texto: "Pon una canción que te recuerde a mí." },
    { id: 37, categoria: "curiosos", texto: "Prepara una bebida con los ingredientes más raros que encuentres." },
    { id: 38, categoria: "curiosos", texto: "Intenta ligar conmigo como si no nos conociéramos." },
    { id: 39, categoria: "curiosos", texto: "Dibuja lo que quieras sobre mi piel con tus dedos." },
    { id: 40, categoria: "curiosos", texto: "Enséñame la parte favorita de tu cuerpo." }
];
